### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [3]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to Change These)
schools = "Resources/schools_complete.csv"
students = "Resources/students_complete.csv"

# Read School and Student Data File and store into Pandas Data Frames
school_data = pd.read_csv(schools)
student_data = pd.read_csv(students)

# Combine the data into a single dataset
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])

school_data_complete

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
5,5,Bryan Miranda,M,9th,Huang High School,94,94,0,District,2917,1910635
6,6,Sheena Carter,F,11th,Huang High School,82,80,0,District,2917,1910635
7,7,Nicole Baker,F,12th,Huang High School,96,69,0,District,2917,1910635
8,8,Michael Roth,M,10th,Huang High School,95,87,0,District,2917,1910635
9,9,Matthew Greene,M,10th,Huang High School,96,84,0,District,2917,1910635
10,10,Andrew Alexander,M,10th,Huang High School,90,70,0,District,2917,1910635
11,11,Daniel Cooper,M,10th,Huang High School,78,77,0,District,2917,1910635
12,12,Brittney Walker,F,9th,Huang High School,64,79,0,District,2917,1910635
13,13,William Long,M,9th,Huang High School,71,79,0,District,2917,1910635
14,14,Tammy Hebert,F,10th,Huang High School,85,67,0,District,2917,1910635
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88,0,District,2917,1910635
16,16,Donald Zamora,M,9th,Huang High School,88,55,0,District,2917,1910635
17,17,Kimberly Santiago,F,9th,Huang High School,74,75,0,District,2917,1910635
18,18,Kevin Stevens,M,9th,Huang High School,64,69,0,District,2917,1910635
19,19,Brandi Lyons,F,9th,Huang High School,89,80,0,District,2917,1910635
20,20,Lisa Davis,F,10th,Huang High School,91,89,0,District,2917,1910635
21,21,Kristen Lopez,F,10th,Huang High School,90,77,0,District,2917,1910635
22,22,Kimberly Stewart,F,11th,Huang High School,99,84,0,District,2917,1910635
23,23,Christopher Parker,M,9th,Huang High School,81,68,0,District,2917,1910635
24,24,Chelsea Griffith,F,11th,Huang High School,85,73,0,District,2917,1910635
25,25,Cesar Morris,M,9th,Huang High School,92,70,0,District,2917,1910635
26,26,Melanie Decker,F,9th,Huang High School,63,85,0,District,2917,1910635
27,27,Tracey Oconnor,F,10th,Huang High School,80,58,0,District,2917,1910635
28,28,Kelly James,F,11th,Huang High School,73,55,0,District,2917,1910635
29,29,Nicole Brown,F,12th,Huang High School,90,88,0,District,2917,1910635
...,...,...,...,...,...,...,...,...,...,...,...
39140,39140,Cheyenne Hernandez,F,9th,Thomas High School,76,99,14,Charter,1635,1043130
39141,39141,Jonathan Sullivan,M,10th,Thomas High School,86,93,14,Charter,1635,1043130
39142,39142,Deborah Higgins DDS,F,10th,Thomas High School,96,83,14,Charter,1635,1043130
39143,39143,Steven Jackson,M,11th,Thomas High School,71,93,14,Charter,1635,1043130
39144,39144,Cristian Webster,M,12th,Thomas High School,77,87,14,Charter,1635,1043130
39145,39145,Audrey Fry,F,10th,Thomas High School,94,74,14,Charter,1635,1043130
39146,39146,Michael Carroll,M,9th,Thomas High School,69,95,14,Charter,1635,1043130
39147,39147,Raymond Hawkins,M,10th,Thomas High School,88,81,14,Charter,1635,1043130
39148,39148,Christopher Wilson,M,10th,Thomas High School,89,89,14,Charter,1635,1043130
39149,39149,Glenda Fletcher,F,11th,Thomas High School,82,93,14,Charter,1635,1043130
39150,39150,Jennifer Hamilton,F,11th,Thomas High School,80,75,14,Charter,1635,1043130
39151,39151,Shannon Williams,F,10th,Thomas High School,84,73,14,Charter,1635,1043130
39152,39152,Lori Moore,F,9th,Thomas High School,98,84,14,Charter,1635,1043130
39153,39153,William Hubbard,M,9th,Thomas High School,80,75,14,Charter,1635,1043130
39154,39154,Bradley Johnson,M,12th,Thomas High School,91,71,14,Charter,1635,1043130
39155,39155,John Brooks,M,10th,Thomas High School,92,98,14,Charter,1635,1043130
39156,39156,Stephanie Contreras,F,11th,Thomas High School,79,95,14,Charter,1635,1043130
39157,39157,Kristen Gonzalez,F,9th,Thomas High School,79,94,14,Charter,1635,1043130
39158,39158,Kari Holloway,F,10th,Thomas High School,87,90,14,Charter,1635,1043130
39159,39159,Kimberly Cabrera,F,11th,Thomas High School,85,72,14,Charter,1635,1043130
39160,39160,Katie Weaver,F,11th,Thomas High School,89,86,14,Charter,1635,1043130
39161,39161,April Reyes,F,10th,Thomas High School,70,84,14,Charter,1635,1043130
39162,39162,Derek Weeks,M,12th,Thomas High School,94,77,14,Charter,1635,1043130
39163,39163,John Reese,M,11th,Thomas High School,90,75,14,Charter,1635,1043130
39164,39164,Joseph Anthony,M,9th,Thomas High School,97,76,14,Charter,1635,1043130
39165,39165,Donna Howard,F,12th,Thomas High School,99,90,14,Charter,1635,1043130
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70,14,Charter,1635,1043130
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84,14,Charter,1635,1043130
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90,14,Charter,1635,1043130
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,14,Charter,1635,1043130

## District Summary

* Calculate the total number of schools

* Calculate the total number of students

* Calculate the total budget

* Calculate the average math score 

* Calculate the average reading score

* Calculate the overall passing rate (overall average score), i.e. (avg. math score + avg. reading score)/2

* Calculate the percentage of students with a passing math score (70 or greater)

* Calculate the percentage of students with a passing reading score (70 or greater)

* Create a dataframe to hold the above results

* Optional: give the displayed data cleaner formatting

In [2]:
#total schools 
total_schools=school_data_complete["School ID"].nunique()
print(total_schools)

15

In [3]:
#total students
total_students=school_data_complete["student_name"].count()
print(total_students)

39170

In [4]:
total_students=school_data_complete["Student ID"].nunique()
print(total_students)

39170

In [5]:
# school budget
total_budget=school_data["budget"].sum()
print(total_budget)

24649428

In [6]:
#math average
math_avg=school_data_complete["math_score"].mean()
print(math_avg)

78.98537145774827

In [7]:
#reading average
reading_avg=school_data_complete["reading_score"].mean()
print(reading_avg)

81.87784018381414

In [8]:
#overall passing rate
overall_rate = (reading_avg + math_avg)/2
print(overall_rate)

80.43160582078121

In [11]:
#Calculate the percentage of students with a passing math score (70 or greater)
passing_students_math = school_data_complete.loc[(school_data_complete["math_score"]>=70)]
count_math = passing_students_math["math_score"].count()
percent_passing_math_score = (count_math/total_students)*100
print(count_math)
print(total_students)
print(percent_passing_math_score)

29370
39170
74.9808526933878

In [12]:
#reading students
passing_students_reading = school_data_complete.loc[(school_data_complete["reading_score"]>=70)]
count_read = passing_students_reading["reading_score"].count()
percent_passing_reading_score = (count_read/total_students)*100
print(count_read)
print(total_students)
print(percent_passing_reading_score)

33610
39170
85.80546336482001

In [18]:
dataframe= pd.DataFrame({"Total Schools": [total_schools],
                         "Total Students": [total_students],
                         "Total Budget": [total_budget],
                         "Average Math Score" : [math_avg],
                         "Average Reading Score" :[reading_avg],
                         "% Passing Math": [percent_passing_math_score],
                         "% Passing Reading":[percent_passing_reading_score],
                         "% Overall Passing Rate": [overall_rate]
                        })

dataframe

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
0,15,39170,24649428,78.985371,81.87784,74.980853,85.805463,80.431606

## School Summary

* Create an overview table that summarizes key metrics about each school, including:
  * School Name
  * School Type
  * Total Students
  * Total School Budget
  * Per Student Budget
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)
  
* Create a dataframe to hold the above results

## Top Performing Schools (By Passing Rate)

* Sort and display the top five schools in overall passing rate

In [5]:
students_per_school=school_data_complete.groupby('school_name')['student_name'].count()
print(students_per_school)

school_name
Bailey High School       4976
Cabrera High School      1858
Figueroa High School     2949
Ford High School         2739
Griffin High School      1468
Hernandez High School    4635
Holden High School        427
Huang High School        2917
Johnson High School      4761
Pena High School          962
Rodriguez High School    3999
Shelton High School      1761
Thomas High School       1635
Wilson High School       2283
Wright High School       1800
Name: student_name, dtype: int64

## Bottom Performing Schools (By Passing Rate)

* Sort and display the five worst-performing schools

## Math Scores by Grade

* Create a table that lists the average Reading Score for students of each grade level (9th, 10th, 11th, 12th) at each school.

  * Create a pandas series for each grade. Hint: use a conditional statement.
  
  * Group each series by school
  
  * Combine the series into a dataframe
  
  * Optional: give the displayed data cleaner formatting

## Reading Score by Grade

* Perform the same operations as above for reading scores

## Scores by School Spending

* Create a table that breaks down school performances based on average Spending Ranges (Per Student). Use 4 reasonable bins to group school spending. Include in the table each of the following:
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)

In [ ]:
# Sample bins. Feel free to create your own bins.
spending_bins = [0, 585, 615, 645, 675]
group_names = ["<$585", "$585-615", "$615-645", "$645-675"]

## Scores by School Size

* Perform the same operations as above, based on school size.

In [ ]:
# Sample bins. Feel free to create your own bins.
size_bins = [0, 1000, 2000, 5000]
group_names = ["Small (<1000)", "Medium (1000-2000)", "Large (2000-5000)"]

## Scores by School Type

* Perform the same operations as above, based on school type.